# Generated by Django 4.0.6 on 2022-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('profile_img', models.URLField()),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_token', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
