# Generated by Django 4.1 on 2022-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
