# Generated by Django 4.1 on 2022-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
